name: wine_rec
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - numpy
    - pandas
    - torch
    - sentence-transformers
    - rsconnect-python
  - r-essentials
  - r-devtools
  - r-shiny